var materialList = [
  // 应急标志灯具
  {
    sp_id: 0,
    sp_img: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/f443043eb0a04ec9bca09afa0c17d169.png",
    sp_name: "消防应急标志灯具",
    sp_version: "GD-BLJC-2LREⅡ1W-401G",
    sp_sold: "111",
    sp_supplier: "北京原杰",
    sp_storage_location: "四川成都",
    sp_new_price: "190",
    sp_old_price: "200",
    sp_unit: "个",
    sp_industry: "消防器材",
    sp_brand: "时代威盾",
    sp_purchase_num: "100",
    sp_size: "365mmX150mmX28mm，功率两总线制；DC36V电压。",
    sp_receive_time: "2019-08-12",
    sp_abort_time: "2019-05-30",
    sp_purchase_type: "单次采购",
    sp_remark: "无",
    sp_order_status: "待接单",
    sp_nstallation: "吊装双面双向",
    sp_intro: "无",
    sp_types: [
      "原厂", "性价比高"
    ],
    sp_offer_area: "全国",
    sp_send_period: "下单后15天内",
    sp_delivery_service: "默认发德邦物流(特殊需求请联系客服)",
  },
  // 应急照明灯具
  {
    sp_id: 1,
    sp_img: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/7cb840bee17446b4ae258dd2575cc58a.png",
    sp_name: "消防应急照明灯具",
    sp_version: "GD-ZFJC-E5W-601G5",
    sp_sold: "222",
    sp_supplier: "北京原杰",
    sp_storage_location: "四川成都",
    sp_new_price: "280",
    sp_old_price: "290",
    sp_unit: "个",
    sp_industry: "消防器材",
    sp_brand: "时代威盾",
    sp_purchase_num: "100",
    sp_size: "265mmX240mmX45mm，功率两总线制；DC36V电压。",
    sp_receive_time: "2019-08-21",
    sp_abort_time: "2019-07-06",
    sp_purchase_type: "单次采购",
    sp_remark: "无",
    sp_order_status: "报价中",
    sp_nstallation: "壁挂",
    sp_intro: "无",
    sp_types: [
      "原厂", "性价比高"
    ],
    sp_offer_area: "全国",
    sp_send_period: "下单后15天内",
    sp_delivery_service: "默认发德邦物流(特殊需求请联系客服)",
  },
  // 碟阀
  {
    sp_id: 2,
    sp_img: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/b1d5c5ec37ab4bb28989c34d921f69ce.png",
    sp_name: "球墨铸铁蝶阀",
    sp_version: "DN200",
    sp_sold: "222",
    sp_supplier: "北京原杰",
    sp_storage_location: "四川成都",
    sp_new_price: "610",
    sp_old_price: "620",
    sp_unit: "套",
    sp_industry: "消防器材",
    sp_brand: "时代威盾",
    sp_purchase_num: "50",
    sp_size: "无",
    sp_receive_time: "2019-11-08",
    sp_abort_time: "2019-09-06",
    sp_purchase_type: "单次采购",
    sp_remark: "无",
    sp_order_status: "待接单",
    sp_nstallation: "无",
    sp_intro: "无",
    sp_types: [
      "原厂", "性价比高"
    ],
    sp_offer_area: "全国",
    sp_send_period: "下单后15天内",
    sp_delivery_service: "默认发德邦物流(特殊需求请联系客服)",
  },
  // 闸阀
  {
    sp_id: 3,
    sp_img: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/75dd61f147eb48fb9397270355045aad.png",
    sp_name: "球墨铸铁闸阀",
    sp_version: "DN300",
    sp_sold: "222",
    sp_supplier: "北京原杰",
    sp_storage_location: "四川成都",
    sp_new_price: "3160",
    sp_old_price: "3167",
    sp_unit: "套",
    sp_industry: "消防器材",
    sp_brand: "时代威盾",
    sp_purchase_num: "80",
    sp_size: "无",
    sp_receive_time: "2019-10-08",
    sp_abort_time: "2019-08-08",
    sp_purchase_type: "单次采购",
    sp_remark: "明杆",
    sp_order_status: "报价中",
    sp_nstallation: "无",
    sp_intro: "无",
    sp_types: [
      "原厂", "性价比高"
    ],
    sp_offer_area: "全国",
    sp_send_period: "下单后15天内",
    sp_delivery_service: "默认发德邦物流(特殊需求请联系客服)",
  },
  // 水表
  {
    sp_id: 4,
    sp_img: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/3336b5112c224de89510c86ce86693e2.png",
    sp_name: "水表",
    sp_version: "DN150",
    sp_sold: "222",
    sp_supplier: "北京原杰",
    sp_storage_location: "四川成都",
    sp_new_price: "550",
    sp_old_price: "560",
    sp_unit: "个",
    sp_industry: "消防器材",
    sp_brand: "甬欣",
    sp_purchase_num: "200",
    sp_size: "无",
    sp_receive_time: "2019-06-08",
    sp_abort_time: "2019-05-01",
    sp_purchase_type: "单次采购",
    sp_remark: "无",
    sp_order_status: "待接单",
    sp_nstallation: "无",
    sp_intro: "无",
    sp_types: [
      "原厂", "性价比高"
    ],
    sp_offer_area: "全国",
    sp_send_period: "下单后15天内",
    sp_delivery_service: "默认发德邦物流(特殊需求请联系客服)",
  },
  // 普通消防栓
  {
    sp_id: 5,
    sp_img: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/6fd5925a80ae4bada5cbcbbb2975ef35.png",
    sp_name: "普通消防栓",
    sp_version: "SN65",
    sp_sold: "555",
    sp_supplier: "北京原杰",
    sp_storage_location: "四川成都",
    sp_new_price: "65",
    sp_old_price: "68",
    sp_unit: "个",
    sp_industry: "消防器材",
    sp_brand: "双龙",
    sp_purchase_num: "200",
    sp_size: "无",
    sp_receive_time: "2019-03-08",
    sp_abort_time: "2019-02-22",
    sp_purchase_type: "单次采购",
    sp_remark: "无",
    sp_order_status: "报价中",
    sp_nstallation: "无",
    sp_intro: "无",
    sp_types: [
      "原厂", "性价比高"
    ],
    sp_offer_area: "全国",
    sp_send_period: "下单后15天内",
    sp_delivery_service: "默认发德邦物流(特殊需求请联系客服)",
  },
  // 消防水带
  {
    sp_id: 6,
    sp_img: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/a0d20e0097be449ea23eab38c3956763.png",
    sp_name: "消防水带",
    sp_version: "25米",
    sp_sold: "123",
    sp_supplier: "北京原杰",
    sp_storage_location: "四川成都",
    sp_new_price: "120",
    sp_old_price: "125",
    sp_unit: "个",
    sp_industry: "消防器材",
    sp_brand: "百应",
    sp_purchase_num: "200",
    sp_size: "无",
    sp_receive_time: "2019-05-02",
    sp_abort_time: "2019-04-06",
    sp_purchase_type: "单次采购",
    sp_remark: "无",
    sp_order_status: "待接单",
    sp_nstallation: "无",
    sp_intro: "无",
    sp_types: [
      "原厂", "性价比高"
    ],
    sp_offer_area: "全国",
    sp_send_period: "下单后15天内",
    sp_delivery_service: "默认发德邦物流(特殊需求请联系客服)",
  },
  // 七氟丙烷灭火系统
  {
    sp_id: 7,
    sp_img: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/21d56714b01b466493290d33fe2704ec.png",
    sp_banner: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/d526408ad9ef4ff78b7fd34644f7a2a3.png",
    sp_name: "5.6/4.2七氟丙烷灭火系统",
    sp_version: "无",
    sp_sold: "123",
    sp_supplier: "陕西坚瑞消防工程有限公司",
    sp_storage_location: "四川成都",
    sp_new_price: "价格面议",
    sp_old_price: "125",
    sp_unit: "套",
    sp_industry: "消防器材",
    sp_brand: "无",
    sp_purchase_num: "1",
    sp_size: "无",
    sp_receive_time: "2019-09-09",
    sp_abort_time: "2019-06-06",
    sp_purchase_type: "单次采购",
    sp_remark: "无",
    sp_order_status: "报价中",
    sp_nstallation: "无",
    sp_types: [
      "原厂", "性价比高"
    ],
    sp_offer_area: "全国",
    sp_send_period: "下单后15天内",
    sp_delivery_service: "默认发德邦物流(特殊需求请联系客服)",
    
  },
  // IG521混合型气体灭火系统
  {
    sp_id: 8,
    sp_img: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/345133cd57d8477182e1fc219ef3e452.png",
    sp_banner: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/72540f7d20d94361ba8bc0d349be10ef.png",
    sp_name: "IG541混合型气体灭火系统",
    sp_version: "无",
    sp_sold: "123",
    sp_supplier: "陕西坚瑞消防工程有限公司",
    sp_storage_location: "四川成都",
    sp_new_price: "价格面议",
    sp_old_price: "125",
    sp_unit: "套",
    sp_industry: "消防器材",
    sp_brand: "无",
    sp_purchase_num: "1",
    sp_size: "无",
    sp_receive_time: "2019-08-20",
    sp_abort_time: "2019-06-20",
    sp_purchase_type: "单次采购",
    sp_remark: "无",
    sp_order_status: "待接单",
    sp_nstallation: "无",
    sp_intro: "IG-541灭火剂由N2、Ar、CO2三种惰性气体按一定比例混合而成。其ODP=0，使用后以其原有成分回归自然，是一种绿色灭火剂，是哈龙灭火剂的理想替代品。无色无味，不导电、无腐蚀、无环保限制，在灭火过程中无任何分解物。IG541的无毒性反应（NOAEL）浓度为43%，有毒性反应（LOAEL）浓度为52%，I IG541设计浓度一般在37%~43%之间，在此浓度内人员短时停留不会造成生理影响，相对安全。",
    sp_types: [
      "原厂", "性价比高"
    ],
    sp_detail_imgs: [
      "/pages/icons/pincl/xtsb_detail_11.png",
      "/pages/icons/pincl/xtsb_detail_12.png",
      "/pages/icons/pincl/xtsb_detail_13.png",
      "/pages/icons/pincl/xtsb_detail_14.png",
    ],
    sp_offer_area: "全国",
    sp_send_period: "下单后15天内",
    sp_delivery_service: "默认发德邦物流(特殊需求请联系客服)",
  },
  // 柜式七氟丙烷灭火装置
  {
    sp_id: 9,
    sp_img: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/ae11d392d82c45c49f15d675da5058ab.png",
    sp_banner: "http://baogongxia1.oss-cn-shenzhen.aliyuncs.com/bgx-admin/20190125/1ca6ab23d36d4c1abb3f0c793cbc45b5.png",
    sp_name: "柜式七氟丙烷灭火装置",
    sp_version: "无",
    sp_sold: "123",
    sp_supplier: "陕西坚瑞消防工程有限公司",
    sp_storage_location: "四川成都",
    sp_new_price: "价格面议",
    sp_old_price: "125",
    sp_unit: "套",
    sp_industry: "消防器材",
    sp_brand: "无",
    sp_purchase_num: "1",
    sp_size: "无",
    sp_receive_time: "2019-08-08",
    sp_abort_time: "2019-06-06",
    sp_purchase_type: "单次采购",
    sp_remark: "无",
    sp_order_status: "报价中",
    sp_nstallation: "无",
    sp_intro: "柜式七氟丙烷灭火装置是将贮存瓶组、管路、喷咀、压力讯号器、阀驱动装a等组件.装在柜件里面的装皿。 柜式七氟丙烷灭火装置为电磁阀启动型.柜体外观设计美观大方.对于不同面积的保护区。可选择不同型号规格的灭火瓶组、柜体。减少占地面积。喷咀采用螺旋式或径向射流型喷咀，使灭火剂喷洒迅速，均匀。施工安装方便.工程投资减少等优点。",
    sp_types: [
      "原厂", "性价比高"
    ],
    sp_detail_imgs: [
      "/pages/icons/pincl/xtsb_detail_21.png",
      "/pages/icons/pincl/xtsb_detail_22.png",
      "/pages/icons/pincl/xtsb_detail_23.png",
      "/pages/icons/pincl/xtsb_detail_24.png",
      "/pages/icons/pincl/xtsb_detail_25.png",
    ],
    sp_offer_area: "全国",
    sp_send_period: "下单后15天内",
    sp_delivery_service: "默认发德邦物流(特殊需求请联系客服)",
    
  },

];

module.exports = {
  materialList: materialList
}
